config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  # /kksitesというURLでアクセスされたらapp/controller/indexアクションを実行するための記述
  #ここではgetなためページを表示するだけである
  #これはホームページを回す所である
  
  resources :kksites do
    # いいね機能を送る部分
    resources :likes, only: [:create, :destroy]
    # コメント機能を送る部分
    resources :comments, only: [:create, :destroy]
    collection do
    # /kksitesというURLでアクセスされたらapp/controller/profileアクションを実行するための記述
    get :profile
    # /kksitesというURLでアクセスされたらapp/controller/kagoshimashiアクションを実行するための記述
    get :kagoshimashi
    # /kksitesというURLでアクセスされたらapp/controller/hiokishiアクションを実行するための記述
    get :hiokishi  
    # /kksitesというURLでアクセスされたらapp/controller/airashiアクションを実行するための記述
    get :airashi
    #他のも同様にすると
    get :kirishimashi
    get :minamisatsumashi
    get :minamikyushushi
    get :makurazakishi
    get :itikikushikinoshi
    get :satsumasendaishi
    get :ibusukishi
    get :satsumatyou
    get :yusuityou
    get :soshi
    get :shibushishi
    get :tarumizushi
    get :kanoyashi
    get :osakityou
    get :higashikushiratyou
    get :akuneshi
    get :izumishi
    get :isashi
    get :nagashimatyou
    get :kimotsukityou
    get :kinkoutyou
    get :minamiosumityou
    # 取り消し機能をするための記述
    
    end
    
    
  end
  # indexの内容が全て終わったあと、自動的に返すための記述
  # ログイン機能からホームページ(つまりここではkksites#index)に移動させるための記述  
  root 'kksites#index'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :kksite
end

app/models/kksite.rb
class Kksite < ApplicationRecord
    belongs_to :user
    
    mount_uploader :image, ImageUploader
    has_many :likes, dependent: :destroy
    has_many :liked_users, through: :likes, source: :user
    has_many :comments, dependent: :destroy
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :kksite
  belongs_to :user

  validates_uniqueness_of :kksite_id, scope: :user_id
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable 

         has_many :kksites, dependent: :destroy

         has_many :likes, dependent: :destroy
         has_many :liked_kksites, through: :likes, source: :kksite
         has_many :comments, dependent: :destroy

  def already_liked?(kksite)
    self.likes.exists?(kksite_id: kksite.id)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end
 

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    before_action :authenticate_user!

    def create
      kksite = Kksite.find(params[:kksite_id])
      comment = kksite.comments.build(comment_params) #buildを使い、contentとtweet_idの二つを同時に代入
      comment.user_id = current_user.id
      if comment.save! #!:セーブせずにスルーしてしまうのを防ぐために書くもの
        flash[:success] = "コメントしました"
        redirect_back(fallback_location: root_path) #直前のページにリダイレクト
      else
        flash[:success] = "コメントできませんでした"
        redirect_back(fallback_location: root_path) #直前のページにリダイレクト
      end
    end
    # コメント機能を消すための記述
    def destroy
      comment = Comment.find(params[:id])
      comment.destroy!
      redirect_to root_path
    end
    private
  
      def comment_params
        params.require(:comment).permit(:cr) #コメント機能のカラム名：cr
      end
end

app/controllers/kksites_controller.rb
class KksitesController < ApplicationController
 
   def index
   end
   def profile
   end
   def new
    @kksite = Kksite.new
   end
   def create
      kksite = Kksite.new(kksite_params)
      # current_user.idはユーザーidを指す
      kksite.user_id = current_user.id
      if kksite.save
        # もし成功したらindexアクションに投稿される
        redirect_to :action => "index"
      else
        redirect_to :action => "new"
      end
    end
   #whereメソッドを使うことで其々のサイト内にあるhtmlの文法つまりdiv要素等を独立させることができる。分かりやすく言うと例えば鹿児島市のサイトに投稿内容が3つあったら3つのdivが反映され、かつ他の市のサイトは鹿児島市のdiv要素が加えられない。鹿児島市のサイトの投稿内容が3つで姶良市のサイトの投稿内容が2つの場合鹿児島市のdiv要素は3つで姶良市のdiv要素は2つでdiv要素が其々の市だけ反映するよう独立している。
   def kagoshimashi
    @kagoshimashi=Kksite.where(cck:"kagoshimashi")
   end
   def hiokishi
    @hiokishi=Kksite.where(cck:"hiokishi")
   end
   def airashi
    @airashi=Kksite.where(cck:"airashi")
   end
   def kirishimashi
    @kirishimahsi=Kksite.where(cck:"kirishimashi")
   end
   def minamisatsumashi
    @minamisatsumashi=Kksite.where(cck:"minamisatsumashi")
   end
   def minamikyushushi
    @minamikyushushi=Kksite.where(cck:"minamikyushushi")
   end
   def makurazakishi
    @makurazakishi=Kksite.where(cck:"makurazakishi")
   end
   def itikikushikinoshi
    @itikikushikinoshi=Kksite.where(cck:"itikikushikinoshi")
   end
   def satsumasendaishi
    @satsumasendaishi=Kksite.where(cck:"satsumasendaishi")
   end
   def ibusukishi
    @ibusukishi=Kksite.where(cck:"ibusukishi")
   end
   def satsumatyou
    @satsumatyou=Kksite.where(cck:"satsumatyou")
   end
   def yusuityou
    @yusuityou=Kksite.where(cck:"yusuityou")
   end
   def soshi
    @soshi=Kksite.where(cck:"soshi")
   end
   def shibushishi
    @shibushishi=Kksite.where(cck:"shibushishi")
   end
   def tarumizushi
    @tarumizushi=Kksite.where(cck:"tarumizushi")
   end
   def kanoyashi
    @kanoyashi=Kksite.where(cck:"kanoyashi")
   end
   def osakityou
    @osakityou=Kksite.where(cck:"osakityou")
   end
   def akuneshi
    @akuneshi=Kksite.where(cck:"akuneshi")
   end
   def izumishi
    @izumishi=Kksite.where(cck:"izumishi")
   end
   def isashi
    @isashi=Kksite.where(cck:"isashi")
   end
   def nagashimatyou
    @nagashimatyou=Kksite.where(cck:"nagashimatyou")
   end
   def kimotsukityou
    @kimotsukityou=Kksite.where(cck:"kimotsukityou")
   end
   def kinkoutyou
    @kinkoutyou=Kksite.where(cck:"kinkoutyou")
   end
   def minamiosumityou
    @minamiosumityou=Kksite.where(cck:"minamiosumityou")
   end
   def higashikushiratyou
    @higashikushiratyou=Kksite.where(cck:"higashikushiratyou")
   end
   # 管理者だけが見れるサイトにデータベースを全て格納させるための記述
   def secrt
    @kksites=Kksite.all
   end
   # 投稿したもの(画像や内容)を消すための記述
   def destroy
    kksite = Kksite.find(params[:id])
    kksite.destroy
    redirect_to action: :index
    
   end
   
  private
   def kksite_params
     params.require(:kksite).permit(:cc,:cck,:image,:user_id)
   end
   
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
      def create
        like = current_user.likes.create(kksite_id: params[:kksite_id]) #user_idとkksite_idの二つを代入
        redirect_back(fallback_location: root_path)
      end
    
      def destroy
        like = Like.find_by(kksite_id: params[:kksite_id], user_id: current_user.id)
        like.destroy
        redirect_back(fallback_location: root_path)
      end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/k_ksite_helper.rb
module KKsiteHelper
end

app/helpers/kksites_helper.rb
module KksitesHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/views/kksites/airashi.html.erb
<div class="airashifile">
<h3>Sightseeing of 姶良市</h3>
</div>
  <!-- 投稿機能 -->
  <% @airashi.each do |t| %>
    <div class="ptars">
    
          <p class="dcrps"><b>内容</b><br><%= t.cc %></p>
          <%= image_tag t.image_url, class:'image' if t.image? %>
          <!-- 投稿内容と画像を削除するための記述(管理者権限の部分) -->
          <% if user_signed_in? %>
           <% if current_user.admin? %> 
             <%= button_to "削除する", kksite_path(t.id), method: :delete %>  
           <% end %>
          <% end %>
     <!-- いいね機能 -->
     <div class="gds">
      <% if user_signed_in? %>
        <% if current_user.already_liked?(t) %>
          <%= button_to kksite_like_path(id: t.id, kksite_id: t.id), method: :delete do %>
            <!-- いいねを取り消す機能の部分 -->
              <i class="fa-solid fa-eraser fa-2x" style="color: #333399"><p class="erase">いいねを取り消す</p></i><br><%= t.likes.count %>
          <% end %>
        <% else %>
          <%= button_to kksite_likes_path(id: t.id, kksite_id: t.id), method: :post do %>
            <!-- いいね機能の部分 -->
              <p><i class="fa-solid fa-thumbs-up fa-2x" style="color: #FF1A6F"></i></p><%= t.likes.count %>
          <% end %>
        <% end %>
      <% else %>
          <p>いいねの数 ↓ </p><%= t.likes.count %>
      <% end %>
     </div>
     <!-- コメント機能 -->
   <div class="comment-wrapper">
     <p class="cmntc">コメント一覧</p>
     <% t.comments.each do |f| %>
       <div>
         <%= f.user.email unless f.user.blank? %>
         <br>
         <%= f.cr %>
         <%= button_to "削除する", kksite_comment_path(t.id, f.id), method: :delete %>
         
       </div>
         <br>
     <% end %>
   
     <% if user_signed_in? %>
       <%= form_with(model: [t,Comment.new ], local: true) do |t| %>
         <%= t.text_area :cr %>
         <%= button_tag type: "submit" do %>
           <i class="fa-regular fa-comments" style="color: #D2691E"></i> 左の欄にコメント書いたらこのボタンを押してね!
         
        <% end %>
       <% end %>
     <% end %>
   </div>
    
  
   </div>  
  <% end %>

      <div class="kgr">
          <%= link_to 'ホームページに戻る',kksites_path %>
      </div>


app/views/kksites/hiokishi.html.erb
<div class="hiokishifile">
<h3>Sightseeing of 日置市</h3>
</div>
  <!-- 投稿機能 -->
  <% @hiokishi.each do |t| %>
   <div class="pthos">
  
          <p class="dcrps"><b>内容</b><br><%= t.cc %></p>
          <%= image_tag t.image_url, class:'image' if t.image? %>
          <!-- 投稿内容と画像を削除するための記述(管理者権限の部分) -->
          <% if user_signed_in? %>
           <% if current_user.admin? %> 
             <%= button_to "削除する", kksite_path(t.id), method: :delete %>  
           <% end %>
          <% end %>
     <!-- いいね機能 -->
     <div class="gds">
      <% if user_signed_in? %>
        <% if current_user.already_liked?(t) %>
          <%= button_to kksite_like_path(id: t.id, kksite_id: t.id), method: :delete do %>
             <!-- いいねを取り消す機能の部分 -->  
                <i class="fa-solid fa-eraser fa-2x" style="color: #333399"><p class="erase">いいねを取り消す</p></i><br><%= t.likes.count %>
          <% end %>
        <% else %>
          <%= button_to kksite_likes_path(id: t.id, kksite_id: t.id), method: :post do %>
           <!-- いいねを取り消す機能の部分 -->  
             <p><i class="fa-solid fa-thumbs-up fa-2x" style="color: #FF1A6F"></i></p><%= t.likes.count %>
          <% end %>
        <% end %>
      <% else %>
          <p>いいねの数 ↓ </p><%= t.likes.count %>
      <% end %>
     </div>
     <!-- コメント機能 -->
   <div class="comment-wrapper">
     <p class="cmntc">コメント一覧</p>
     <% t.comments.each do |f| %>
       <div>
         <%= f.user.email unless f.user.blank? %>
         <br>
         <%= f.cr %>
         <%= button_to "削除する", kksite_comment_path(t.id, f.id), method: :delete %>
         
       </div>
         <br>
     <% end %>
   
     <% if user_signed_in? %>
       <%= form_with(model: [t,Comment.new ], local: true) do |t| %>
         <%= t.text_area :cr %>
         <%= button_tag type: "submit" do %>
          <!-- コメントする機能の部分 -->
           <i class="fa-regular fa-comments" style="color: #D2691E"></i> 左の欄にコメント書いたらこのボタンを押してね!
        <% end %>
       <% end %>
     <% end %>
   </div>
    
  
   </div>  
  <% end %>
 
      <div class="kgr">
          <%= link_to 'ホームページに戻る',kksites_path %>
      </div>
   </div>




app/views/kksites/isashi.html.erb
<div class="isashifile">
<h3>Sightseeing of 伊佐市</h3>
</div>
  <!-- 投稿機能 -->
  <% @isashi.each do |t| %>
   <div class="ptiss">
    
          <p class="dcrps"><b>内容</b><br><%= t.cc %></p>
          <%= image_tag t.image_url, class:'image' if t.image? %>
          <!-- 投稿内容と画像を削除するための記述(管理者権限の部分) -->
          <% if user_signed_in? %>
           <% if current_user.admin? %> 
             <%= button_to "削除する", kksite_path(t.id), method: :delete %>  
           <% end %>
          <% end %>
     <!-- いいね機能 -->
     <div class="gds">
      <% if user_signed_in? %>
        <% if current_user.already_liked?(t) %>
          <%= button_to kksite_like_path(id: t.id, kksite_id: t.id), method: :delete do %>
           <!-- いいねを取り消す機能の部分 --> 
              <i class="fa-solid fa-eraser fa-2x" style="color: #333399"><p class="erase">いいねを取り消す</p></i><br><%= t.likes.count %>
          <% end %>
        <% else %>
          <%= button_to kksite_likes_path(id: t.id, kksite_id: t.id), method: :post do %>
           <!-- いいね機能の部分 -->   
              <p><i class="fa-solid fa-thumbs-up fa-2x" style="color: #FF1A6F"></i></p><%= t.likes.count %>
          <% end %>
        <% end %>
      <% else %>
          <p>いいねの数 ↓ </p><%= t.likes.count %>
      <% end %>
     </div>
     <!-- コメント機能 -->
   <div class="comment-wrapper">
     <p class="cmntc">コメント一覧</p>
     <% t.comments.each do |f| %>
       <div>
         <%= f.user.email unless f.user.blank? %>
         <br>
         <%= f.cr %>
         <%= button_to "削除する", kksite_comment_path(t.id, f.id), method: :delete %>
         
       </div>
         <br>
     <% end %>
   
     <% if user_signed_in? %>
       <%= form_with(model: [t,Comment.new ], local: true) do |t| %>
         <%= t.text_area :cr %>
         <%= button_tag type: "submit" do %>
          <!-- コメントする機能の部分 -->
           <i class="fa-regular fa-comments" style="color: #D2691E"></i> 左の欄にコメント書いたらこのボタンを押してね!
         
        <% end %>
       <% end %>
     <% end %>
   </div>
    
    
   </div>  
  <% end %>  
      <div class="kgr">
          <%= link_to 'ホームページに戻る',kksites_path %>
      </div>
   </div>




app/views/kksites/izumishi.html.erb
<div class="izumishifile">
<h3>Sightseeing of 出水市</h3>
</div>
     <!-- 投稿機能 -->
     <% @izumishi.each do |t| %>
      <div class="ptim">
       
        <p class="dcrps"><b>内容</b><br><%= t.cc %></p>
        <%= image_tag t.image_url, class:'image' if t.image? %>
        <!-- 投稿内容と画像を削除するための記述(管理者権限の部分) -->
        <% if user_signed_in? %>
         <% if current_user.admin? %> 
           <%= button_to "削除する", kksite_path(t.id), method: :delete %>  
         <% end %>
        <% end %>
   <!-- いいね機能 -->
   <div class="gds">
    <% if user_signed_in? %>
      <% if current_user.already_liked?(t) %>
        <%= button_to kksite_like_path(id: t.id, kksite_id: t.id), method: :delete do %>
         <!-- いいねを取り消す機能の部分 -->
            <i class="fa-solid fa-eraser fa-2x" style="color: #333399"><p class="erase">いいねを取り消す</p></i><br><%= t.likes.count %>
        <% end %>
      <% else %>
        <%= button_to kksite_likes_path(id: t.id, kksite_id: t.id), method: :post do %>
         <!-- いいね機能の部分 -->
             <p><i class="fa-solid fa-thumbs-up fa-2x" style="color: #FF1A6F"></i></p><%= t.likes.count %>
        <% end %>
      <% end %>
    <% else %>
        <p>いいねの数 ↓ </p><%= t.likes.count %>
    <% end %>
   </div>
   <!-- コメント機能 -->
 <div class="comment-wrapper">
   <p class="cmntc">コメント一覧</p>
   <% t.comments.each do |f| %>
     <div>
       <%= f.user.email unless f.user.blank? %>
       <br>
       <%= f.cr %>
       <%= button_to "削除する", kksite_comment_path(t.id, f.id), method: :delete %>
       
     </div>
       <br>
   <% end %>
 
   <% if user_signed_in? %>
     <%= form_with(model: [t,Comment.new ], local: true) do |t| %>
       <%= t.text_area :cr %>
       <%= button_tag type: "submit" do %>
        <!-- コメントする機能の部分 -->
          <i class="fa-regular fa-comments" style="color: #D2691E"></i> 左の欄にコメント書いたらこのボタンを押してね!
       
      <% end %>
     <% end %>
   <% end %>
 </div>
  
 
 </div> 
<% end %>
    <div class="kgr">
        <%= link_to 'ホームページに戻る',kksites_path %>
    </div>
 </div>







app/views/kksites/kagoshimashi.html.erb
<!-- 鹿児島市のサイトの編集する部分 -->
<div class="kagoshimashifile">
<h3>Sightseeing of 鹿児島市</h3>
</div>
       <!-- 投稿機能 -->
    <!-- もし、7行目の上に<div class="ptkgs">と置くと投稿全てに箱として囲まれてしまい例えば3つ投稿した場合、デザインで枠を作る時、1つ枠で3つの投稿を全て囲む形になるので見栄えのいいデザインになりにくい --> 
  <% @kagoshimashi.each do |t| %>
 <div class="ptkgs"> <!-- 7行目の下に<div class="ptkgs">と置くことで一つ一つの投稿にデザインすることができる -->
   
            <p class="dcrps"><b>内容</b><br><%= t.cc %></p>
            <%= image_tag t.image_url, class:'image' if t.image? %>
            <!-- 投稿内容と画像を削除するための記述(管理者権限の部分) -->
            <% if user_signed_in? %>
              <% if current_user.admin? %>
                 <%= button_to "削除する", kksite_path(t.id), method: :delete %>
              <% end %>
            <% end %>
       <!-- いいね機能 -->
       <div class="gds">
        <% if user_signed_in? %>
          <% if current_user.already_liked?(t) %>
            <%= button_to kksite_like_path(id: t.id, kksite_id: t.id), method: :delete do %>
              <!-- いいねを取り消す機能の部分 -->
                 <i class="fa-solid fa-eraser fa-2x" style="color: #333399"><p class="erase">いいねを取り消す</p></i><br><%= t.likes.count %> 
            <% end %>
          <% else %>
            <%= button_to kksite_likes_path(id: t.id, kksite_id: t.id), method: :post do %>
              <!-- いいね機能の部分 -->
                 <p><i class="fa-solid fa-thumbs-up fa-2x" style="color: #FF1A6F"></i></p><%= t.likes.count %>
            <% end %>
          <% end %>
        <% else %>
            <p>いいねの数 ↓ </p><%= t.likes.count %>
        <% end %>
       </div>
       <!-- コメント機能 -->
     <div class="comment-wrapper">
       <p class="cmntc">コメント一覧</p>
       <% t.comments.each do |f| %>
         <div>
           <%= f.user.email unless f.user.blank? %>
           <br>
           <%= f.cr %>
           <%= button_to "削除する", kksite_comment_path(t.id, f.id), method: :delete %>
           
         </div>
           <br>
       <% end %>
     
       <% if user_signed_in? %>
         <%= form_with(model: [t,Comment.new ], local: true) do |t| %>
           <%= t.text_area :cr %>
           <%= button_tag type: "submit" do %>
            <!-- コメントする機能の部分 -->
            <i class="fa-regular fa-comments" style="color: #D2691E"></i> 左の欄にコメント書いたらこのボタンを押してね!
           
          <% end %>
         <% end %>
       <% end %>
     </div>
      

   </div> <!-- 60行目の上に</div>と置くことで一つ一つの投稿にデザインすることができる -->
  <% end %>
   <!-- もし、60行目の下に</div>と置くと投稿全てに箱として囲まれてしまい例えば3つ投稿した場合、デザインで枠を作る時、1つ枠で3つの投稿を全て囲む形になるので見栄えのいいデザインになりにくい --> 
      <div class="kgr">
          <%= link_to 'ホームページに戻る',kksites_path %>
      </div>
   

app/views/kksites/minamikyushushi.html.erb
<div class="minamikyushushifile">
<h3>Sightseeing of 南九州市</h3>
</div>
  <!-- 投稿機能 -->
  <% @minamikyushushi.each do |t| %>
    <div class="ptmkss">
   
          <p class="dcrps"><b>内容</b><br><%= t.cc %></p>
          <%= image_tag t.image_url, class:'image' if t.image? %>
          <!-- 投稿内容と画像を削除するための記述(管理者権限の部分) -->
          <% if user_signed_in? %>
           <% if current_user.admin? %> 
             <%= button_to "削除する", kksite_path(t.id), method: :delete %>  
           <% end %>
          <% end %>
     <!-- いいね機能 -->
     <div class="gds">
      <% if user_signed_in? %>
        <% if current_user.already_liked?(t) %>
          <%= button_to kksite_like_path(id: t.id, kksite_id: t.id), method: :delete do %>
           <!-- いいねを取り消す機能の部分 -->   
              <i class="fa-solid fa-eraser fa-2x" style="color: #333399"><p class="erase">いいねを取り消す</p></i><br><%= t.likes.count %>
          <% end %>
        <% else %>
          <%= button_to kksite_likes_path(id: t.id, kksite_id: t.id), method: :post do %>
           <!-- いいね機能の部分 -->   
              <p><i class="fa-solid fa-thumbs-up fa-2x" style="color: #FF1A6F"></i></p><%= t.likes.count %>
          <% end %>
        <% end %>
      <% else %>
          <p>いいねの数 ↓ </p><%= t.likes.count %>
      <% end %>
     </div>
     <!-- コメント機能 -->
   <div class="comment-wrapper">
     <p class="cmntc">コメント一覧</p>
     <% t.comments.each do |f| %>
       <div>
         <%= f.user.email unless f.user.blank? %>
         <br>
         <%= f.cr %>
         <%= button_to "削除する", kksite_comment_path(t.id, f.id), method: :delete %>
         
       </div>
         <br>
     <% end %>
   
     <% if user_signed_in? %>
       <%= form_with(model: [t,Comment.new ], local: true) do |t| %>
         <%= t.text_area :cr %>
         <%= button_tag type: "submit" do %>
           <!-- コメントする機能の部分 -->
             <i class="fa-regular fa-comments" style="color: #D2691E"></i> 左の欄にコメント書いたらこのボタンを押してね!
        <% end %>
       <% end %>
     <% end %>
   </div>
    
  
   </div> 
  <% end %>
      <div class="kgr">
          <%= link_to 'ホームページに戻る',kksites_path %>
      </div>
   </div>



app/views/kksites/minamiosumityou.html.erb
<div class="minamiosumityoufile">
<h3>Sightseeing of 南大隅町</h3>
</div>
  <!-- 投稿機能 -->
  <% @minamiosumityou.each do |t| %>
    <div class="ptmost">
   
          <p class="dcrps"><b>内容</b><br><%= t.cc %></p>
          <%= image_tag t.image_url, class:'image' if t.image? %>
          <!-- 投稿内容と画像を削除するための記述(管理者権限の部分) -->
          <% if user_signed_in? %>
           <% if current_user.admin? %> 
             <%= button_to "削除する", kksite_path(t.id), method: :delete %>  
           <% end %>
          <% end %>
     <!-- いいね機能 -->
     <div class="gds">
      <% if user_signed_in? %>
        <% if current_user.already_liked?(t) %>
          <%= button_to kksite_like_path(id: t.id, kksite_id: t.id), method: :delete do %>
           <!-- いいねを取り消す機能の部分 -->   
             <i class="fa-solid fa-eraser fa-2x" style="color: #333399"><p class="erase">いいねを取り消す</p></i><br><%= t.likes.count %>
          <% end %>
        <% else %>
          <%= button_to kksite_likes_path(id: t.id, kksite_id: t.id), method: :post do %>
           <!-- いいね機能の部分 --> 
              <p><i class="fa-solid fa-thumbs-up fa-2x" style="color: #FF1A6F"></i></p><%= t.likes.count %>
          <% end %>
        <% end %>
      <% else %>
          <p>いいねの数 ↓ </p><%= t.likes.count %>
      <% end %>
     </div>
     <!-- コメント機能 -->
   <div class="comment-wrapper">
     <p class="cmntc">コメント一覧</p>
     <% t.comments.each do |f| %>
       <div>
         <%= f.user.email unless f.user.blank? %>
         <br>
         <%= f.cr %>
         <%= button_to "削除する", kksite_comment_path(t.id, f.id), method: :delete %>
         
       </div>
         <br>
     <% end %>
   
     <% if user_signed_in? %>
       <%= form_with(model: [t,Comment.new ], local: true) do |t| %>
         <%= t.text_area :cr %>
         <%= button_tag type: "submit" do %>
           <!-- コメントする機能の部分 -->
             <i class="fa-regular fa-comments" style="color: #D2691E"></i> 左の欄にコメント書いたらこのボタンを押してね!
        <% end %>
       <% end %>
     <% end %>
   </div>
    
  
   </div>  
  <% end %>
      <div class="kgr">
          <%= link_to 'ホームページに戻る',kksites_path %>
      </div>
   </div>



app/views/kksites/secrt.html.erb
<!-- 管理者しか見れないサイト -->
<h3>管理者用サイト</h3>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= button_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), data: { turbo: false } %><br />
  <% end %>
<% end %>